### ISSUE TITLE
Feature suggestion: Create pages from data not in /content

### ISSUE THREAD

**Issue by tgelu** [dillonkearns/elm-pages#108]
I find myself needing to create pages from data from an API. At first I thought it was as simple as generating files with `Pages.Platform.withFileGenerator generateFiles`, but I learned that was a wrong assumption.

At the moment I have some script which I run before building which writes files into the `content` folder. This works but it is far from ideal for many reasons.

It would be immensely helpful if I could fetch data from wherever at build time and use that data to generate not only files but actual pages and routes, just as if they were in the `content`.

I can't imagine this is trivial to implement, but I had to submit it here for the record :)

**Comment by tgelu** [comment]
I've just notice this one https://github.com/dillonkearns/elm-pages/issues/76 :sweat_smile:

**Comment by dillonkearns** [comment]
Yeah, you've got it exactly right, that's the current workaround, and it will be a non-trivial change, but it's a very high priority. I can't wait to get that functionality! There will be a few steps to get there, but it's definitely on the roadmap.
