### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gDelgado14** [dillonkearns/elm-pages#12]
In https://elm-pages.com/blog/introducing-elm-pages there was a "Next Steps" section that mentioned some super exciting features. In particular I think

> Allow users to pass a set of HTTP requests to fetch during the build step (for making CMS or API data available statically in the build)

.. is super exciting! Very much like gatsby! Would be cool to connect to Contentful or other headless CMS! 

Secondly, do you intend on publishing a prioritized roadmap?

**Comment by dillonkearns** [comment]
There's a lot going on here, but you can see the work in progress here if you're curious! 😄 

https://github.com/dillonkearns/elm-pages/compare/static-http?expand=1

Good idea about the public roadmap, I think that would be great. I'll put that together when I get a chance to catch up on things a bit. Thanks for the suggestion!

**Comment by dillonkearns** [comment]
Oh, and by the way, the static-http branch is just the first step... that's to prove out the concept. But eventually I'll be working on not just being able to have data that you fetch for a given page, but being able to create pages based on that data. But this is a good first step to validate some of the design (and a nice feature, too, I hope!)

**Comment by dillonkearns** [comment]
Here's a roadmap for the what I've got on my todo list for the StaticHttp API 😄

https://github.com/dillonkearns/elm-pages/projects/1

**Comment by dillonkearns** [comment]
I'll close this issue though there's always more that can be done with sharing what's going on. I'll try to keep what I'm working on, and what my priorities are, relatively updated on Github so others can get an idea of what to expect. I also added a link to the Github projects in the readme: https://github.com/dillonkearns/elm-pages/blob/master/README.md#whats-next

Thanks again for the suggestion!

**Comment by dillonkearns** [comment]
I added a roadmap to keep track of the work in progress of the big picture and the little tasks, too 👍

👍

**Comment by dillonkearns** [comment]
I added a roadmap to keep track of the work in progress of the big picture and the little tasks, too 👍

https://github.com/dillonkearns/elm-pages/projects/2
