### ISSUE TITLE
Some head content being duplicated after being pre-rendered

### ISSUE THREAD

**Issue by bobcats** [dillonkearns/elm-pages#124]
When looking at the source html for https://elm-pages.com/, you can see some tags being duplicated, for example:

```html
<meta name="generator" content="elm-pages v1.4.1">
```

If you disable JavaScript and reload the page, note there are no duplicates, which leads me to believe that this is because the prerendering step adds the tags, and then on page load they are added again.

**Comment by dillonkearns** [comment]
Thanks for the report @bobcats! 🙏

If you're interested in trying out the no-webpack beta build, that should fix that problem! https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-ELM.md#700---2020-10-26

**Comment by dillonkearns** [comment]
I'll close this issue since I believe it's fixed in the new beta build. But feel free to re-open or open a new thread if there are any issues or if you have questions. Thank you!
