### ISSUE TITLE
Build error with manifest description containing an exclamation mark

### ISSUE THREAD

**Issue by ringods** [dillonkearns/elm-pages#146]
I am struggling with an `elm-pages build` problem, which doesn't happen when running `elm-pages develop`.

Looking at the error message, I have the impression there is something not being quoted well:

```
(node:8468) UnhandledPromiseRejectionWarning: Error: Can't resolve '","developerName":null,"developerURL":null,"dir":"auto","lang":"en-US","background":"#ffffff","theme_color":"#ffffff","appleStatusBarStyle":"black-translucent","display":"standalone","orientation":"portrait","scope":"/","start_url":"","version":"1.0","logging":true,"pixel_art":false,"loadManifestWithCredentials":false,"icons":{"android":true,"appleIcon":true,"appleStartup":false,"coast":false,"favicons":true,"firefox":false,"windows":false,"yandex":false}},"path":"","outputPath":""}' in '/Users/ringods/Projects/personal/ringo_de_smet_name'
```

If I take the string after Can't resolve until the end, it seems to be a JSON piece, but not well-balanced:

```
","developerName":null,"developerURL":null,"dir":"auto","lang":"en-US","background":"#ffffff","theme_color":"#ffffff","appleStatusBarStyle":"black-translucent","display":"standalone","orientation":"portrait","scope":"/","start_url":"","version":"1.0","logging":true,"pixel_art":false,"loadManifestWithCredentials":false,"icons":{"android":true,"appleIcon":true,"appleStartup":false,"coast":false,"favicons":true,"firefox":false,"windows":false,"yandex":false}},"path":"","outputPath":""}
```

I dug a bit further: the item in the JSON just before the developerName is the appDescription, according to this piece of source: 

https://github.com/dillonkearns/elm-pages/blob/646ebc42b2f77103e8e4a1d4fe68ec0c07ba624a/generator/src/develop.js#L235

This comes in from the manifestConfig , so I went to look for the value of it in my site setup: 

https://github.com/ringods/ringo_de_smet_name/commit/59837b264f87195cd9a20f95d057e1573e32df17

Dropping the exclamation mark at the end of the string made elm-pages build work now. After discussing this with @dillonkearns on the #elm-pages channel of the Elm Slack, he pointed me out to this underlying webpack plugin issue:

https://github.com/jantimon/favicons-webpack-plugin/issues/204

Yet another reason to drive #140 forward. 😉

**Comment by dillonkearns** [comment]
Hello @ringods, if you're up for trying out the new beta build, that will be replacing `elm-pages build` and I believe this will fix the error you're describing here 😄 

Here are the instructions for using the new beta build: https://github.com/dillonkearns/elm-pages/blob/master/docs/7.0.0-elm-package-upgrade-guide.md#2---beta-build-command.

I'll close this issue since the fix is now available, but if you run into any issues or have more questions, feel free to re-open or create a new issue. Thank you!

**Comment by ringods** [comment]
Hello @dillonkearns, I finally found the time to bump to 7.0.0 and the beta build.

https://github.com/ringods/ringo_de_smet_name/commit/222abf4dae66342acbf11ceab2d3d807bc030bfc

So far so good. Next days/weeks slowly changing styling, slug structure etc to mimic the current style.
