### ISSUE TITLE
Support sites hosted not at the top level

### ISSUE THREAD

**Issue by ianmackenzie** [dillonkearns/elm-pages#15]
Currently it is possible to create `elm-pages` sites at URLs like `example.net` but not `example.net/some/subdir`, since functions like `ImagePath.toString` and `PagePath.toString` return URLs of the form

```
/images/some_image.png
/some_page
```
instead of

```
/some/subdir/images/some_image.png
/some/subdir/some_page
```

or

```
https://example.net/some/subdir/images/some_image.png
https://example.net/some/subdir/some_page
```

(Specifically, I was unable to create a working `elm-pages` site at https://ianmackenzie.github.io/elm-geometry/guide.)

**Comment by dillonkearns** [comment]
Hey @ianmackenzie! I just released @icidasset's fix for this 👍 

[NPM package version](1.2.12](https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-NPM.md#1212---2020-03-28) and [Elm package version 4.0.1](https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-ELM.md#401---2020-03-28).

**Comment by ianmackenzie** [comment]
Yeah, saw that on Slack! Fantastic work in #73, quite the epic discussion =)
