### ISSUE TITLE
`elm-pages build` and `elm-pages develop` fail with "Input image exceeds pixel limit" when there is an SVG in the images directory

### ISSUE THREAD

**Issue by dbj** [dillonkearns/elm-pages#158]
`elm-pages build` and `elm-pages develop` fail with "Input image exceeds pixel limit" when there is an SVG in the images directory:

## Steps to Reproduce

1. put an SVG file in the `<project-root>/images` directory
2. Run `elm-pages develop` or `elm-pages build`

Example output:

```bash
$ npx elm-pages develop
🚀 elm-pages develop on http://localhost:3000
webpack built 75012ccc433bf1fb250a in 1113ms
✖ ｢wdm｣: 
ERROR in Error: Input image exceeds pixel limit
ℹ ｢wdm｣: Failed to compile.
```

and

```bash
$ npx elm-pages build
[Error: Input image exceeds pixel limit]
```

## Configuration

I'm running elm-pages npm package "1.5.4", and elm-pages Elm package "7.0.0". I'm running on macOS Big Sur 11.1 on Apple Silicon (M1).

## Fix

Unfortunately, this requires I put the SVG in the `static` dirctory, bypassing the nice type assurances of the `images` directory.

**Comment by dbj** [comment]
Here is the SVG file causing the issue: 
[training.svg.zip](https://github.com/dillonkearns/elm-pages/files/6137567/training.svg.zip)

**Comment by dillonkearns** [comment]
I believe `sharp` was running against that file and causing that issue, and `sharp` is no longer a dependency for the latest 2.0 NPM package, so this shouldn't be an issue going forward 👍
