### ISSUE TITLE
Environment specific configuration

### ISSUE THREAD

**Issue by mcasper** [dillonkearns/elm-pages#160]
Hey folks! I'm sure I'm missing something basic here, but I'm hitting a wall trying to figure out how to have environment specific configurations with elm-pages (dev vs prod).

My specific use case: I've got an API server I need to talk to dynamically, which will be at `localhost:<port>` in development, and `<my_special_domain>` in production. Normally I would detect what environment I'm in using `NODE_ENV` and a flag, but it looks like flags are currently not allowed in elm-pages. I then thought I could maybe use Pages.Secrets to consume the domain in an environment variable, but it looks like those only work with StaticHttp requests.

I'm not sure what the ideal solution would be (or if there already is one), but right now I'm doing some hacky code-gen tacked before the `elm-pages develop` and `elm-pages build` commands.

Any help with this issue would be appreciated 🙏

**Comment by dillonkearns** [comment]
Hey @mcasper! 👋

I've thought about this and it could make for a good feature at some point. I'm overall really happy with the design of the Secrets API, but as you say it doesn't cover the use case of environment variables that aren't secrets.

I think in the meantime, a good way to work with this would be with a little script (Node or bash) to generate an Elm module.

It could look something like this:

```javascript
#!/usr/bin/env node

const fs = require("fs");

const expectedEnvironmentVariables = process.argv.slice(2);

const topLevelDefinitions = expectedEnvironmentVariables.map(
  (envVariableName) => {
    const envVariableValue = process.env[envVariableName];
    if (envVariableValue) {
      return `
${envVariableName} : String
${envVariableName} =
    "${envVariableValue}"`;
    } else {
      throw new Error(
        `I couldn't find an environment variable with the name ${envVariableName}`
      );
    }
  }
);

const moduleContent = `module Env exposing (${expectedEnvironmentVariables.join(
  ", "
)})

${topLevelDefinitions}
`;

fs.writeFileSync("./Env.elm", moduleContent);
```

This could also fit well as a separate NPM tool and be included in the `elm-pages-starter` 🤔 Hope that script is helpful!

**Comment by dillonkearns** [comment]
And by the way, you run the script with `chmod +x ./build-env.js` (or whatever file you save it as) and then `./build-env.js ENV_VAR_1 ENV_VAR_2`.

I didn't go to the trouble to normalize the environment variable names to be valid Elm names, so you would need to have them start with a lowercase letter (you could either use some prefix, like `var_${...}`, or some other convention like converting it to camel case).

**Comment by dillonkearns** [comment]
And it looks like there's an NPM package that does exactly this! 😄 

https://github.com/jaredramirez/elm-constants

**Comment by dillonkearns** [comment]
You can also use `DataSource.Port` in the latest 2.0 NPM package/8.0 Elm package. Here's an example:

https://github.com/dillonkearns/incremental-elm-web/blob/7f96255b22faf28bd1f7531486b28d5fdb56a935/port-data-source.js#L17-L28

https://github.com/dillonkearns/incremental-elm-web/blob/7f96255b22faf28bd1f7531486b28d5fdb56a935/src/Page/PortExample.elm#L55-L59

I think that should cover it pretty nicely!
