### ISSUE TITLE
Security Vulnerability - dependency:  url-regex

### ISSUE THREAD

**Issue by GaryBozek** [dillonkearns/elm-pages#162]
When attempting to use `elm-pages-starter`, I got the following error on command `npm install`:

![Screenshot from 2021-02-18 15-15-32](https://user-images.githubusercontent.com/63157712/108434514-a2aee400-71fc-11eb-8787-01d267e8ba4b.png)

**Comment by dillonkearns** [comment]
In general, these audit warnings are typically false positives in this package. See https://overreacted.io/npm-audit-broken-by-design/.

Also, I just removed a whole lot of NPM dependencies and updated to new versions of the packages that the 2.0.0 NPM package depends on 👍
