### ISSUE TITLE
Elm-Pages requires Python.

### ISSUE THREAD

**Issue by Erudition** [dillonkearns/elm-pages#163]
Just thought it should be mentioned somewhere that if you try to run `elm-pages build` without an executable in your path named "python", one of the dependencies will complain and it will fail.

This means it can't be run on many distros or docker images, I discovered -- without first installing python.

**Comment by schoening** [comment]
@Erudition which version? I have python 3 installed and still get this error. So not only that we need python but also if it is 2 or 3.

**Comment by dillonkearns** [comment]
The dependency that caused issues before in `elm-pages` was `sharp`. It has native dependencies, and for some users it was finicky when installing.

I just published the 2.0.0 NPM package/8.0.0 Elm package, and the sharp and webpack dependencies are completely gone! So I think installation should be smooth on all systems at this point. If you do happen to run into any problems with the 2.0+ NPM package, please let me know! I'll close this for now. Thanks!
