### ISSUE TITLE
Use TypeScript for index.ts

### ISSUE THREAD

**Issue by peteralbert** [dillonkearns/elm-pages#177]
Is there any way to use TypeScript for the index.ts file? While the Elm part is pretty stable, we've been running into issue outside the ports that TypeScript would have easily prevented...

Thanks for the great work!

**Comment by dillonkearns** [comment]
Hey Peter! I'll share our discussion from Slack here for reference.

I laid out the high-level philosophy here: https://github.com/dillonkearns/elm-pages/issues/148

The basic idea is that elm-pages v2 doesn't do any of the JavaScript bundling at all. It gives a single entrypoint file, index.js. You can add a webpack step to transpile to index.js. But as far as elm-pages is concerned, the only thing it knows how to handle is:

- Build a full-featured Elm site (bundle, minify, etc. all of the Elm code, build an Elm SPA, do the routing, everything related to an Elm app)
- Include an index.js file (no processing whatsoever)


The problem with the traditional approach that some tools, like Gatsby, for example take, is that they let you extend webpack, which then lets you mess with the internals in ways that could break things. So it's a leaky abstraction. So the solution that I went with is that `elm-pages` is completely agnostic about those things, it just takes a single JavaScript entrypoint and lets the user handle that however they want. This also means that users don't have to incur the additional complexity and build times from Webpack or similar tools if they don't need the complexity. And they're not stuck with the opinions or specific features that `elm-pages` builds for bundling JS/CSS, etc, but instead they can use whatever solution they want.

**Comment by dillonkearns** [comment]
Oh yes, and it's also worth giving this blog post a read:

https://incrementalelm.com/tips/typescript-without-transpilation/

I've been using that technique on almost all of my projects, and I find that it gives me 90% of the value of TypeScript.
