### ISSUE TITLE
Netlify deploys fail during npm run build

### ISSUE THREAD

**Issue by mtimbs** [dillonkearns/elm-pages#204]
For some reason, I cannot get elm-pages to build with Netlify. I've tried numerous tweaks to no avail. You can see failed build logs [here](https://app.netlify.com/sites/heuristic-minsky-1ed6b4/deploys/611bdc9d8f8fab000805ddd1) which is driven by [netlify.toml](https://github.com/mtimbs/blog-elm-pages/blob/main/netlify.toml)

It generates all the static files correctly but then exits with code 1.

When I run `npm run build` locally everything works as expected and I get the exact same log messages except without the non-zero exit status. As I cannot seem to see any steps between where Netlify gets to, and the final output stage I am at a loss where to go from here. The `netlify.toml` matches closely the one used for Docs/blog here.

I've installed the Netlify CLI to do a manual deploy from a local build which worked as expected. I also ran `netlify build` via the CLI to see if I got any more useful information and I did get an extra error message - unfortunately, no extra logs were generated

**Comment by danmarcab** [comment]
Hi @mtimbs , I've run into similar problems and making sure netlify is using a newer version of node (16 in my case) worked for me. Just thought you might give it a try
