### ISSUE TITLE
Content edits are not reloaded in dev mode

### ISSUE THREAD

**Issue by danmarcab** [dillonkearns/elm-pages#22]
When you make a change in a content file (markdown for example), you can see in the console `elm-pages is watching the files and running:

```
Rerunning for content/posts/post.md
Running elm-pages...
Done!
elm-pages DONE
ℹ ｢wdm｣: Compiling...
Started compiling Elm..
ℹ ｢wdm｣: Compiled successfully.
```

The sequence in the output suggest `elm-pages` is doing its thing, then `webpack` is noticing the change and building.

Unfortunately if you reload the page in the browser, the changes are not there, you only see a blank page (not even the old state).

You need to restart elm-pages to see the content.

NOTES:
- Changing an `.elm` file and reloading the page works fine.
- According to the discussion in slack, @dillonkearns thinks this is probably
  `webpack` and `elm-pages` stepping on each other's toes.

@dillonkearns thank you again for the great work you are doing! If you want help I'd love to give it a try, pointers welcome because I am definitely not a `webpack` expert :)

**Comment by dillonkearns** [comment]
This should be working now! https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-NPM.md#115---2020-01-03
