### ISSUE TITLE
Query Params for Current Page

### ISSUE THREAD

**Issue by heath** [dillonkearns/elm-pages#24]
Hey @dillonkearns I'd like to grab the query params for the current page being viewed. The use case I'm thinking through is that there are a list of items (credit cards e.g.) on a page, and clicking on an item will take the user to another page which will have actions the user may take associated with the item on the previous page. I was thinking one approach to this might be to pass an identifier in the query params. Enjoy your vacation, and I'll catch you when you're back!

**Comment by dillonkearns** [comment]
Hey @heath! What do you think of this as an API?

```elm
init :
    Maybe
        { path : PagePath Pages.PathKey
        , query : Maybe String
        , fragment : Maybe String
        }
    -> ( Model, Cmd Msg )
```

```elm
OnPageChange
        { path : PagePath Pages.PathKey
        , query : Maybe String
        , fragment : Maybe String
        }
```

You register the OnPageChange msg in `Pages.Platform.application`. Would love to hear if you think this addresses your use case well!

https://github.com/dillonkearns/elm-pages/pull/39/files#diff-cd29c18a68bc5b4e4bea6fd393dc6b99L83-R99

**Comment by heath** [comment]
@dillonkearns That makes sense to me. Let's try it out!

**Comment by dillonkearns** [comment]
For future reference here, from a discussion on Slack... the record for `OnPageChange` here is trying to match [`elm/url`'s `Url` type](https://package.elm-lang.org/packages/elm/url/latest/Url#Url) with the type and name of the fields `query` and `fragment` (it just passes them through):

```elm
type alias Url =
    { protocol : Protocol
    , host : String
    , port_ : Maybe Int
    , path : String
    , query : Maybe String
    , fragment : Maybe String
    }
```
