### ISSUE TITLE
`Html.Lazy` doesn't pre-render

### ISSUE THREAD

**Issue by TSFoster** [dillonkearns/elm-pages#240]
If using `Html.Lazy` (also `Html.Styled.Lazy`), pages render fine once the JS is loaded, but the pre-rendering in the build step doesn't work (even through the build succeeds). The error always looks something like:

```
      Error: Problem with the given value:

{
        "$": 5,
        "l": [
            null,
            {
                "$": 1,
                "a": {
                    "$": 4,
                    "k": {
                        "$": 0,
                        "a": "Index"
                    },
                    "b": 1
                },
                "b": {
                    "$": 0,
                    "a": null,
                    "b": null
                }
            }
        ]
    }

Expecting an OBJECT with a field named `node`
```

## Steps to reproduce

1. `init` new project
2. Change `Shared.view` to use `Html.Lazy.lazy` somewhere

```bash
#!/usr/bin/env bash
npx elm-pages init elm-pages-lazy-test
cd elm-pages-lazy-test
npm install
echo -n "Checking fresh install build … "
npm run build 2>&1 > /dev/null
grep -q '<div>Index</div>' dist/index.html && echo "Success!" || echo "Fail!"
echo -n "Checking with Html.Lazy … "
# import Html.Lazy.lazy and use it with (Html.div [])
cat src/Shared.elm | sed 's/import Html/import Html.Lazy exposing (lazy)\nimport Html/g' | sed 's/body = Html.div \[\]/body = lazy (Html.div [])/g' > src/SharedNew.elm
mv src/SharedNew.elm src/Shared.elm
npm run build 2>&1 > /dev/null
grep -q '<div>Index</div>' dist/index.html && echo "Success!" || echo "Fail!"
echo "See dist/index.html for details"
```

**Comment by dillonkearns** [comment]
After a little investigation, it looks like it's a more involved change to make the lazy HTML render eagerly.

It looks like there is some kernel code in the `elm-explorations/test` repo to help with this to force the thunks to evaluate: https://github.com/elm-explorations/test/blob/d5eb84809de0f8bbf50303efd26889092c800609/src/Elm/Kernel/HtmlAsJson.js#L21.

Here is a related PR for dealing with the thunks in elm-test: https://github.com/eeue56/elm-html-test/pull/7.

So it seems like the fix might be to include that `forceThunks` function in the CLI code as part of this step that tweaks the compiled output: https://github.com/dillonkearns/elm-pages/blob/7d25c16ee8131fce149b8334c983d7a5ed9f611c/generator/src/build.js#L351-L352.
