### ISSUE TITLE
Feature request: Markdown Image as Link on Showcase Page

### ISSUE THREAD

**Issue by PixelPartner** [dillonkearns/elm-pages#244]
Dear Dillon,

I realised that I constantly expect a tap/click on a thumbnail at your showcase page will bring me to the same destination page as the link below it. It's frustrating.

I heard your podcast about elm-markdown and how sprinkling in HTML can mess up everything.
Sigh - but I hope you pros find a way

**Comment by dillonkearns** [comment]
Thanks for the feedback, I turned those showcase thumbnails into links 👍  By the way, it's not markdown on this page, the data is coming from the Airtable API (users can submit to the showcase through a form and it gets added to airtable after I click a button to accept the entry to make sure it's not spam) 😄 

https://github.com/dillonkearns/elm-pages/blob/7ebcd9f3144d2a605dfd8f613e4876284ed3a683/examples/docs/src/Showcase.elm#L39-L52
