### ISSUE TITLE
port-data-source cannot import relative paths

### ISSUE THREAD

**Issue by j-maas** [dillonkearns/elm-pages#283]
I cannot use a relative import in `port-data-source.ts` like `import { destinationFolder, getSizes } from "./scripts/processImages";` because the compiled script is in a different directory:

```
-- DataSource.Port Error --------------- 
DataSource.Port.send "imageSources" was called, but I couldn't import the port definitions file, because of this exception: `Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\Johannes\Code\elm-pages-3-alpha-starter\.elm-pages\compiled-ports\scripts\processImages' imported from C:\Users\Johannes\Code\elm-pages-3-alpha-starter\.elm-pages\compiled-ports\port-data-source-LYB5KFI5.mjs` Are there syntax errors or exceptions thrown during import?
```

In the [dev-server code](https://github.com/dillonkearns/elm-pages/blob/ef6f80ff01d501661de0cda9c88595d035634f7a/generator/src/dev-server.js#L152) I tried setting `bundle: true` and `platform: true`, but it appears this compiles to CJS which cannot be imported still:

```
-- DataSource.Port Error --------------- 
DataSource.Port.send "imageSources" was called, but I couldn't import the port definitions file, because of this exception: `ReferenceError: module is not defined` Are there syntax errors or exceptions thrown during import?
```

I'm not sure what the solution to this issue is.

**Comment by dillonkearns** [comment]
I'll take a deeper look at this, thank you for reporting the issue! 🙏

**Comment by j-maas** [comment]
I can work around this for now by importing the script relative to `./elm-pages/compiled-ports/`, i.e. `import { destinationFolder, getSizes } from "../../scripts/processImages.mjs";`.

**Comment by dillonkearns** [comment]
Hello @j-maas, I believe I've resolved this (though it's a bit tricky so there may still be some details to work out). Could you give it a try and let me know your thoughts? Thank you!

**Comment by dillonkearns** [comment]
You can try in the latest starter repo (I updated it today so it's on the latest code): https://github.com/dillonkearns/elm-pages-3-alpha-starter.

**Comment by j-maas** [comment]
I'm currently really busy, but I'll make a note. I'm happy to try it. 😉

**Comment by j-maas** [comment]
Modified the latest starter repo's port-data-source.ts to load a function from a different file and it works. 👍

**Comment by dillonkearns** [comment]
Excellent, thank you for confirming!
