### ISSUE TITLE
Elm application initialized after each link click

### ISSUE THREAD

**Issue by synalysis** [dillonkearns/elm-pages#29]
It would be great if the navigation would work without page reloads so that application state is kept.

Some API that allows the application to switch to another page would be good. And the links in Markdown pages should use this API instead of the default link behavior.

Is this a reasonable request?

**Comment by dillonkearns** [comment]
Hello!

Could you give a little more context on where you're seeing this behavior? I just did a little test (here's the code https://github.com/dillonkearns/elm-pages-starter/pull/5/files) and I was able to navigate around to different pages and see it maintaining the counter's state across page changes.

Thank you!

**Comment by dillonkearns** [comment]
Here's a deployed version of that branch: https://5e0fe86642b27a00075b1db9--elm-pages-starter.netlify.com/. You can try clicking (directly on the number in the top left), and then click around to blog posts, etc.

**Comment by synalysis** [comment]
The problem actually "works" with your test: simply go to https://5e0fe86642b27a00075b1db9--elm-pages-starter.netlify.com/blog and click the Blog link in the header menu.

**Comment by synalysis** [comment]
Do I have a chance to switch pages after an Element.Events.onClick event without a page reload?

Currently I'm using Browser.Navigation.load because I don't have the Browser.Navigation.Key for Browser.Navigation.pushUrl.

The reason I'm not using a link here is that when I display a submenu with Element.below the link event  of the submenu items is propagated to the element that displays the submenu and thus never the link of the submenu is followed but the one of the menu item above.

**Comment by dillonkearns** [comment]
Ah, yes, okay thanks for clarifying that!

There's a tricky corner case that I'm working around with the `elm/browser` package's link handling (see https://github.com/elm/browser/issues/39):

https://github.com/dillonkearns/elm-pages/blob/1319d635e02f63076db78c0d49a5b2f65e94cdde/src/Pages/Internal/Platform.elm#L367-L375

Actually, this might be as simple as just running that special case logic for forcing a reload only when it's on the same page (as it does now), *but* the URL has changed.

For example,

`/blog/hello#heading-one` => `/blog/hello#heading-two`
We need to force a page load to cause Elm to correctly go to that anchor tag on the page (it won't cause a reload and this is already working).

`/blog/` => `/blog/`
This is where the incorrect behavior happens. We should change this and just skip the `Browser.Navigation.load` side effect in the update function in this case.

I'll give that a shot!

**Comment by dillonkearns** [comment]
I published a fix for this: https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-ELM.md#111---2020-01-04

Thank you for reporting it and helping me narrow it down!

**Comment by synalysis** [comment]
Thanks a lot for the quick solution, making elm-pages even more mature :-)
