### ISSUE TITLE
Starter repo build fails

### ISSUE THREAD

**Issue by j-maas** [dillonkearns/elm-pages#293]
I am working on a migration to elm-pages 3.0 based on the starter repo. I'm running Windows. I noticed that the build fails, so I switched to https://github.com/dillonkearns/elm-pages-3-alpha-starter/tree/3658c808e905e0337cfb7866669b5c686e759237 and it seems that the build fails there too:

```
$ npm run build

> build
> elm-pages build

No `elm-pages.config.mjs` file found. Using default config.
vite v2.9.4 building for production...
<script src="/elm.js"> in "/elm-stuff/elm-pages/index.html" can't be bundled without type="module" attribute
✓ 5 modules transformed.
dist/elm-stuff\elm-pages\index.html   0.91 KiB
dist/manifest.json                    0.20 KiB
dist/assets/index.b727cb87.js         2.14 KiB / gzip: 1.11 KiB
dist/assets/index.1b505cb2.css        0.12 KiB / gzip: 0.12 KiB
{"type":"error","title":"ERROR WHEN RUNNING ELM-FORMAT","path":"elm.json","message":["I got an unexpected error when running elm-format:\n\nDas System kann den angegebenen Pfad nicht finden."]}
```
("Das System kann den angegebenen Pfad nicht finden." means "The system can't find the given path.")

I have tried `lamdera reset`, but the error message stays the same.

**Comment by dillonkearns** [comment]
Hey @j-maas, thanks for reporting the issue. Could you try it out on the latest starter repo (https://github.com/dillonkearns/elm-pages-3-alpha-starter) and let me know the status if it's not too much trouble? Thank you!

**Comment by j-maas** [comment]
I just cloned the latest starter repo and with `npm install` and `npm run start` it fires up elm-pages correctly. 👍

**Comment by dillonkearns** [comment]
Great, thanks for trying it out!
