### ISSUE TITLE
Decouple the compilation of a generator from the generation of a static page

### ISSUE THREAD

**Issue by tad-lispy** [dillonkearns/elm-pages#301]
I'm looking for a way to reuse the same Elm Pages code with different content. We have a number of repositories with different content (markdown files, etc) but the same general structure. We want to have a single Elm Pages project with Elm code that given a content in right format generates a static page. The generation should be initiated from the content repository (in a CI pipeline for example). 

We are open to other solutions, but it seems to me that the most straight forward way would be to compile the Elm Pages project into a stand-alone program that could be installed and used with different content. It seems that something similar is already happening in the `generator/src/build.js`, specifically the `compileCliApp` function. But I don't see a way of separating the compilation process from the generation of a static page.

I imagine the following (simplified) workflow with the new `compile` command to the `elm-pages` program:

```
shared-elm-pages-project $ elm-pages compile
# creates the generator/ directory with a Node.js program that can be used to generate different static pages
shared-elm-pages-project $ cd ../content-repository-a/
content-repository-a $ cp --recursive ../shared-elm-pages-project/generator ./generator/
# This is a simplified installation step
content-repository-a $ ./generator/generate .
# creates the content-repository-a/dist/ directory with static assets
```

The installation in this example is simplified because in reality we would use a package manager (Nix) to make the generator available when preparing the content. Other users could use different methods. But to be able to do that we need a way to decouple the compilation of a generator from running it.

Would you be interested in a PR to this effect? Is there anything we should take into consideration when working on it?

**Comment by dillonkearns** [comment]
Hey there,

I'm having a little trouble understanding what problem you're encountering here, could you elaborate? What issue do you have from running an elm-pages project with two different sets of content? How does this effect users or developers?

Thanks!

**Comment by tad-lispy** [comment]
Hey, Dillon! Thank you for taking the time to look at the issue. I'm sorry it is not clear. After reading your comment I returned here several times, but I could not think of a way to make it more clear than in my original post. The problem is not relevant to me anymore so I'm going to close it.
