### ISSUE TITLE
CSS Hot Reloading does not work in Firefox

### ISSUE THREAD

**Issue by jreusch4** [dillonkearns/elm-pages#341]
I've just noticed that hot-reloading does not work in Firefox while trying to setup esbuild.

It looks like reloading uses a trick from stackoverflow:

https://github.com/dillonkearns/elm-pages/blob/8d43732fcc12510471ddc0a8d38ef30506693ada/generator/static-code/hmr.js#L52-L59

This does not cause the CSS file to reload in Firefox (106.0.1, Linux x64), but still works in Chrome(ium) for me. Updating a version query param (`?v=1`) still works, other similar tricks I've tried don't:

* Toggling styles by removing `rel` or setting `media` does not work
* Removing an re-inserting the link node does not work

**Comment by jreusch4** [comment]
No longer an issue in elm-pages-3 :)

**Comment by dillonkearns** [comment]
Great, thank you for checking and following up! It now uses Vite for CSS hot reloading.
