### ISSUE TITLE
Libraries in npm packages are not available.

### ISSUE THREAD

**Issue by ababup1192** [dillonkearns/elm-pages#352]
I read the following blog
https://elm-pages.com/blog/introducing-v2

The program here did not work, has anything changed?

```
const kleur = require("kleur");
// this example uses kleur to add ANSI color codes
// They're just strings, so you can use your preferred tool
// or skip it altogether if you don't care about color output

module.exports = {
  environmentVariable: async function (name) {
    const result = process.env[name];
    if (result) {
      return result;
    } else {
      throw `No environment variable called ${kleur
        .yellow()
        .underline(name)}\n\nAvailable:\n\n${Object.keys(process.env).join(
        "\n"
      )}`;
    }
  },
};
```

Errors are here.

```
Uncaught ReferenceError: require is not defined
    at index.js:14:15
```

I am trying to create an authentication mechanism using firebase, is it possible?

**Comment by dillonkearns** [comment]
Hi @ababup1192, could you ask this question in the `#elm-pages` channel on the Elm slack? There's not enough context here to answer the question, and Slack is a better place for going back and forth to get the relevant context, and it also gives other people the opportunity to help answer the question which is helpful for me. Thank you!
