### ISSUE TITLE
Navigation not working on Safari

### ISSUE THREAD

**Issue by brettkolodny** [dillonkearns/elm-pages#367]
I noticed that navigation on the official site doesn't work on Safari (both mobile and desktop). With a little more digging I found it also doesn't work on several other sites featured in the showcase.

Looking at the console it seems to be caused by:

```
TypeError: undefined is not an object (evaluating 't.childNodes')
```

**Comment by brettkolodny** [comment]
No browser extensions and I'm currently on Safari `Version 16.2 (18614.4.1)`. But trying again now it looks like everything is now working on both mobile and desktop for me too. Not sure if maybe I was on an even older version last I tried. Closing the issue but thanks for taking a look!

**Comment by dillonkearns** [comment]
Okay, good to know, thank you for reporting back!
