### ISSUE TITLE
Broken link in elm pages docs site

### ISSUE THREAD

**Issue by aszenz** [dillonkearns/elm-pages#380]
In the page https://elm-pages.com/docs/use-the-platform/, there is a link to https://elm-pages.com/docs/forms, which shows this error:

![Screenshot from 2023-06-03 10-45-44](https://github.com/dillonkearns/elm-pages/assets/25319264/310516c8-eda7-4d27-abd1-5f944addd7f5)

The link is here:
![Screenshot from 2023-06-03 10-44-42](https://github.com/dillonkearns/elm-pages/assets/25319264/b5609d71-4c0a-499b-ae5a-6b25a8bb8045)

**Comment by dillonkearns** [comment]
Thank you for pointing that out! I fixed the link, I changed the Form docs to live in the Elm package docs page for `Pages.Form` instead so that's where that lives.
