### ISSUE TITLE
Windows path error when running elm-pages dev

### ISSUE THREAD

**Issue by mystique09** [dillonkearns/elm-pages#384]
My node version is node v18, tried node v20 it's still the same, even in windows 11.
![image-6.png](https://github.com/dillonkearns/elm-pages/assets/50514928/ff9a9d4b-bfb3-49f8-8922-c30f23587d53)

**Comment by jigargosar** [comment]
any fixes or workarounds?

**Comment by dillonkearns** [comment]
Hello @mystique09, thank you for reporting the issue. I believe ef6bbdbfcca6d823e9b52a862339fed342e03801 fixes this particular issue. However, there may be other places that come up after this fix, and I don't have a Windows machine to test it out.

Would you mind trying NPM package version 3.0.8 and letting me know if it's working now or if you hit a new error? Thank you!

**Comment by mystique09** [comment]
> Hello @mystique09, thank you for reporting the issue. I believe ef6bbdbfcca6d823e9b52a862339fed342e03801 fixes this particular issue. However, there may be other places that come up after this fix, and I don't have a Windows machine to test it out.
> 
> Would you mind trying NPM package version 3.0.8 and letting me know if it's working now or if you hit a new error? Thank you!

Update: it's working now 🥳. Thank you so much for the fix!

**Comment by dillonkearns** [comment]
Wonderful, thanks so much for checking! 🙏
