### ISSUE TITLE
Create a standalone exe version of elm-pages

### ISSUE THREAD

**Issue by MartinSStewart** [dillonkearns/elm-pages#392]
Would it make sense to have a stand alone exe version of elm-pages? 

The advantage to having it is that the user doesn't need to worry about NPM or Node dependencies and can instead just download an exe version of elm-pages directly and run it from their CLI.

It seems like this is possible to do with https://nodejs.org/api/single-executable-applications.html#single-executable-application-creation-process. Assuming this makes sense for elm-pages then I guess the ideal approach would be to add a CI build step to generate the exe for Mac, Linux, and Windows on each elm-pages release.

Related issue: https://github.com/jfmengels/node-elm-review/issues/136

**Comment by dillonkearns** [comment]
If this could be fully automated then it could be worthwhile, but it's not something I have bandwidth to work on and I would only want to accept a PR for this if it is a fully automated, push button process. I'd also want to understand the tradeoffs with regard to things like portability to platforms that an executable is not built for (current niche platforms or future platforms). And also the tradeoffs with regard to the size of the installed executable or any maintenance burden.

**Comment by MartinSStewart** [comment]
I agree, it would have to be completely automated.

Regarding portability/support for niche/future platforms, I don't know what's possible but even if we suppose there is no support at all outside of Mac, Linux, Windows those users can still resort to the normal NPM package. Adding an exe download shouldn't negatively affect the experience for those users.

**Comment by dillonkearns** [comment]
Just to keep the noise down on this repo, I'm going to close this since I don't see it as a priority that I'll tackle, and it doesn't seem like something that would happen in the near-term. Feel free to re-open if you ever start exploring it and it becomes more concrete, though.
