### ISSUE TITLE
`____elm-pages-internal____/404` breaks routes following the pattern `:a/:b`

### ISSUE THREAD

**Issue by georgesboris** [dillonkearns/elm-pages#398]
## The problem

This current internal behavior causes an internal path to be included as one of the pre-rendered paths. https://github.com/dillonkearns/elm-pages/blob/77a4b350338b6109b10876ba3ce3e23f0dd17224/generator/src/build.js#L321-L327 

The problem happens if the user has a route such as `:category/:article`. Then, the pre-render function will be called with `{ category = "____elm-pages-internal____/404", article = "404" }` which will probably break the build since invalid HTTP requests will be triggered with those values as parameters.

## Temporary Workaround

That is exactly what happened in my use case. As a temporary workaround I've used this strategy:

```elm
type Data
    = Valid Article
    | Invalid

data : RouteParams -> BackendTask FatalError Data
data params =
    if params.article == "404" && String.contains "elm-pages-internal" params.category then
        BackendTask.succeed Invalid

    else
        fetchArticle params
```

Then I can deal with the invalid state easily without blocking the rest of the build process.

**Comment by dillonkearns** [comment]
Published with version 3.0.7. Thanks so much for reporting the issue!

I'll have to loop back around and explore ways to do this properly in the future, but for now it's at parity with what v2 did.
