### ISSUE TITLE
"error while loading shared libraries" in Netlify build

### ISSUE THREAD

**Issue by jreusch4** [dillonkearns/elm-pages#418]
Hi,

I was on vacation last week, so I don't know the exact time when this broke. It looks like either Lamdera published a new version, or Netlify changed something in their build container. My last build was at Aug 13, which worked. Now, all builds on Netlify fail with the following error:

```
7:27:49 PM: Trace: /opt/build/repo/bin/lamdera: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
7:27:49 PM:     at Module.run (file:///opt/build/repo/node_modules/elm-pages/generator/src/build.js:297:13)
7:27:49 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
7:27:49 PM:     at async Command.<anonymous> (file:///opt/build/repo/node_modules/elm-pages/generator/src/cli.js:49:7)
7:27:49 PM: /opt/build/repo/bin/lamdera: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

(I've attached the full build log below)

I've tried to restart the build with and w/o the build cache.

Thank you for your help,
joshi

[build-log.txt](https://github.com/dillonkearns/elm-pages/files/12421830/7.27.51.PM.Failed.during.txt)

**Comment by supermario** [comment]
Hey @jreusch4 – it appears that netlify must have changed the platform & upgraded the available version of libtinfo, as it's revealed the URL being used here was not the correct one (pointing to a v1.0.1 binary of Lamdera, before the elm-pages support).

After speaking with Dillon on Slack, I've updated the broken path (https://static.lamdera.com/bin/linux/lamdera) to point to the same binary as the correct current version path for linux (https://static.lamdera.com/bin/lamdera-1.1.0-linux-x86_64).

This should mean re-running your build should just work now – as the correct release is statically compiled and doesn't rely on dynamic libs.

**Comment by dillonkearns** [comment]
Thanks so much for helping me get to the bottom of that @supermario! And thank you for reporting the issue @jreusch4!

The download links I was using in some of the code should have been using versioned lamdera releases. I fixed that in the starter repo here: https://github.com/dillonkearns/elm-pages-starter/commit/4ea9ef40a7c08c067ebf1e19d991ffc45f6b2c27. Mario was kind enough to update the `https://static.lamdera.com/bin/linux/lamdera` URL to point to the latest 1.1.0 Lamdera release as well now, so if you retry your Netlify deploy (assuming you had the same URL that I had in the starter repo there), it should be working again.

I would recommend changing to the versioned URL to make it more stable to point to the locked in version for future reference: https://static.lamdera.com/bin/linux/lamdera.

**Comment by jreusch4** [comment]
I've tried the old download link and that one seems to work again, too. Thank you for your quick response!
