### ISSUE TITLE
Missing Content message flashes on initial load

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-pages#42]
Here are some ideas on how to approach this.

## What's happening now

1. Browser loads and renders the HTML
1. Since the `<script>` tag that includes the Elm bundle is in the `<head>`, and doesn't have a `defer` on it, I believe it will block the rest of the HTML from rendering? (need to confirm this)
1. As the page is loading, we see this message briefly as it fetches the `content.json` file, which contains the body of our content, as well as any `StaticHttp` data for the page:
  https://github.com/dillonkearns/elm-pages/blob/7eaea5dace58d27a2891b8fa3d59ed718c36dd35/src/Pages/Internal/Platform.elm#L156
1. The page fully loads and displays correctly

## Possible solution

1. Render the HTML content immediately (ensure that the Elm bundle doesn't block HTML rendering, but ideally it should also be fetched concurrently as the HTML is rendered... possibly using a `<script defer ...>`?).
1. Pass in some flags to the low-level `elm-pages` `init` that contains already-fetched `content.json` data (could either hardcode that data into the generated HTML file, but probably best and most performant to fetch it once the HTML is rendered, and then callback once it's fetched to init the elm app with that data as a flag).
1. Now, when the Elm app takes over, it has all the data it needs so the "Missing content" message won't flash because the content is present on init from the flag

## Old solution idea
~What could happen instead (this is just one solution path)~ I thought this would be a good approach, but thought of the simpler solution above
1. Render the HTML content immediately (ensure that the Elm bundle doesn't block HTML rendering, but ideally it should also be fetched concurrently as the HTML is rendered... possibly using a `<script defer ...>`?).
1. Render the Elm view off in an invisible `<div>` (will this cause rendering to differ at all? Probably not because it's Elm, right, so it should render reliably even off in an invisible div?).
1. Listen for the Elm `view` function in the invisible `<div>` to be called... can use the MutationObserver technique similar to how `elm-pages` currently listens for page changes in order to know when the URL has changed
  https://github.com/dillonkearns/elm-pages/blob/5754bfb1866c388c5e6891494a7342b44c917dd3/index.js#L72-L84
1. Once the view has been rendered, remove the visible, server-rendered view, and show the hidden, client-rendered view (will this cause any reflow or other kinds of jank? Is there a way to prevent that?)

**Comment by icidasset** [comment]
I've been thinking a bit about this, and I think I have another solution.

1. We don't need to load Elm immediately, since the html file already has the correct content
2. We load the `content.json` file in javascript.
3. When the content has been loaded, load up Elm with the content as a flag. This'll replace the static html.

My only worry here is, will users see a "flash" when the content is being replaced?
What do you think, is this a viable solution?

**Comment by dillonkearns** [comment]
Hello @icidasset, thanks for chiming in! That's actually exactly what's happening in the prototype I have here: https://5e20f901469a7c0008528294--elm-pages.netlify.com/blog/introducing-elm-pages/

You can see the moment when Elm takes over is when the counter starts going up (if you throttle your connection, you can see it even better). There was some discussion in the Elm slack by the way about the idea of not calling the user's `update` function during the pre-render phase at all, which would prevent the number in the pre-rendered HTML from showing up as a 5 (it would be a 0 instead), and then starting out from 0 when Elm takes over.

If you pull up that link and open up your favorite browser performance inspection tools, I'd love to hear what you think of the current state! It seems pretty smooth other than a small flash of the image when Elm takes over (I'm sure there are other blemishes for different types of content like animations, for example, since Elm is actually considering the DOM to be brand new rather than adopting the old one).

**Comment by icidasset** [comment]
Oh, for real? Great 😄

> There was some discussion in the Elm slack by the way about the idea of not calling the user's update function during the pre-render phase at all

Yeah, that seems like a great idea, could possibly prevent some weird situations.

> It seems pretty smooth other than a small flash of the image when Elm takes over

It does feel pretty smooth yeah!
Great work @dillonkearns 👏
