### ISSUE TITLE
npx elm-pages-beta doesn't work anymore

### ISSUE THREAD

**Issue by stefanwouldgo** [dillonkearns/elm-pages#420]
Hi, I've been using elm-pages-beta (between elm-pages v1 and v2) for a stable project since 2021. Unfortunately, now when I simply want to rebuild my page using `npx elm-pages-beta,` I get the following error:
```npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/elm-pages-beta - Not found
npm ERR! 404
npm ERR! 404  'elm-pages-beta@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Is there a way to keep using this version? I have already tried and failed to switch my entire code to v2 a year ago or so, and I am not motivated to try again with v3.

Thank you

**Comment by dillonkearns** [comment]
Hello @stefanwouldgo, the beta was published under the same NPM package with a beta tag. The previous beta releases are all still there: https://www.npmjs.com/package/elm-pages?activeTab=versions. For example, `npx elm-pages@3.0.0-beta.42` is the last published beta version. The Elm package for the v3 beta was https://package.elm-lang.org/packages/dillonkearns/elm-pages-v3-beta/latest/.

I'm not sure which v1/v2 beta you have in mind, but I don't believe anything was ever published on an NPM package name other than `elm-pages`. Whatever version you were using I would think you would be able to see in your package.json, though. I'll close this issue for now, but feel free to send another message on the `#elm-pages` slack channel or post another comment here if that doesn't answer it.
