### ISSUE TITLE
Runtime exception caused by SubmitEvent not being supported on older browsers

### ISSUE THREAD

**Issue by shahnhogan** [dillonkearns/elm-pages#427]
Hi! I'm getting the following error while testing on iOS 14.X devices:

```
ReferenceError: Can't find variable: SubmitEvent
```

It looks like `SubmitEvent` is [not supported on iOS 14](https://caniuse.com/mdn-api_submitevent) or earlier. This causes a runtime exception. I've verified a simple fix of checking to ensure "SubmitEvent" is on the window. I wasn't sure if you wanted a quick PR for the check or were interested in a polyfill.

[generator/static-code/elm-pages.js on line 106
](https://github.com/dillonkearns/elm-pages/blob/679c37f598adbc5f35b647a4331d83d3143ca2f7/generator/static-code/elm-pages.js#L106)
```javascript
if ("SubmitEvent" in window) { ... }
```

If you are OK with a quick PR I would be happy to help, thanks!

**Comment by dillonkearns** [comment]
Published! Thanks for verifying. Let me know how it looks with the latest release when you get a chance: https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-NPM.md#309---2023-10-24

**Comment by shahnhogan** [comment]
It works as expected, thank you!

**Comment by dillonkearns** [comment]
Great, thanks for confirming!
