### ISSUE TITLE
reStructuredText

### ISSUE THREAD

**Issue by ghost** [dillonkearns/elm-pages#43]
I see that Markdown is supported:

https://elm-pages.com/blog/extensible-markdown-parsing-in-elm

Is reStructuredText supported?

https://docutils.sourceforge.io/docs/user/rst/quickref.html

**Comment by dillonkearns** [comment]
Hello! `elm-pages` gives you a hook where you can provide any function that takes a `String` (representing the body of the page) and gives you your view. That's how I hook in my custom `elm-markdown` parser that I built to suite my preferences. So it's fully extensible! You just need a function that parses it. I don't think there's a parser for that in Elm, but you could certainly write one yourself if you want to tackle that. It's a lot of work, though! So if you can, I would try to just use markdown, but don't let me stop you if you want to go and build a parser of your own 😄

**Comment by dillonkearns** [comment]
I'll close this issue, but feel free to reopen it or ping me on the Elm slack if you'd like to discuss anything further!
