### ISSUE TITLE
Replace StaticHttp examples in BackendTask

### ISSUE THREAD

**Issue by tanyabouman** [dillonkearns/elm-pages#433]
I was trying to figure out [`BackendTask.map2`](https://package.elm-lang.org/packages/dillonkearns/elm-pages/latest/BackendTask#map2), and I realized that the documentation example still uses `StaticHttp.map2`.

Then I tried to figure out how to update it, but I found the example difficult to follow. I found a pokedex example more useful. 
https://github.com/dillonkearns/elm-pages/blob/6f1d060148bb023e58295d5b3f19ed797513046f/examples/pokedex/app/Route/Index.elm#L49-L56 Maybe it's worth replacing the example?

The documentation for [`BackendTask.succeed`](https://package.elm-lang.org/packages/dillonkearns/elm-pages/latest/BackendTask#succeed) also references `StaticHttp`, and I found an example on the elm-pages site much easier.
https://github.com/dillonkearns/elm-pages/blob/685f0efc28d53ec2318a1aadaaa3c89f08ae6809/examples/docs/app/Route/Index.elm#L139-L140 

I'm can make the changes, but I'd like feedback on changing the examples and whether there might be better ones.

**Comment by dillonkearns** [comment]
Hello @tanyabouman, thanks for pointing out the issue! I like the idea to use a more meaningful example while also fixing the old API reference. That sounds like a good plan to me, I would very much welcome a PR for that!
