### ISSUE TITLE
Scroll is reset on back navigation

### ISSUE THREAD

**Issue by j-maas** [dillonkearns/elm-pages#437]
I noticed a few issues with how back navigation is handled with respect to scrolling.

1. When I scroll down on a page, open a link, and using the browser's back button go back to the previous page, the scroll position is reset to the top of the page. Normal browser behavior is to remember the scroll position when navigation back.
1. When I click the back button, there is a short flash where it seems that the page is scrolled to the top and then the content is changed. Ideally, the content change and scrolling would happen simultaneously.

For handling the scroll restauration on back navigation, [react-router seems to follow this strategy](https://github.com/remix-run/react-router/blob/4475b56d2e18014acfb8ff5f6077ff27df98d7fe/packages/react-router-dom/index.tsx#L1627):

1. On each navigation, store the scroll position in session storage.
    - This probably is not necessary for fragment changes, because to my knowledge the browser can handle those even in single page application, since they usually happen on the same (logical) page.
1. When navigating back, the scroll position is retrieved from the session storage and scrolled to.
    - It might be necessary to set [`history.scrollRestoration` to `manual`](https://developer.mozilla.org/en-US/docs/Web/API/History/scrollRestoration) to prevent clashes with the browser's behavior.

**Comment by Strepto** [comment]
This was discussed a bit in #294 if that can be of any help. 

I did not resolve it though. (I reported is as a end-user and not a developer. I have not actually used elm-pages )
