### ISSUE TITLE
Blog post has broken Ellie

### ISSUE THREAD

**Issue by Y0hy0h** [dillonkearns/elm-pages#49]
The blog post https://elm-pages.com/blog/extensible-markdown-parsing-in-elm#markdownwithinhtmltags has a broken Ellie that doesn't compile.

I guess that `dillonkearns/elm-markdown` had a breaking update where the [`Renderer`](https://package.elm-lang.org/packages/dillonkearns/elm-markdown/latest/Markdown-Parser#Renderer) now expects both unordered and ordered lists instead of a generic list.

I managed to finally fix some issues where the types weren't right but the parser's error message didn't really help... Here's the fixed Ellie: https://ellie-app.com/7PKpvc4brDCa1 I might open a PR later, when I find the time.

**Comment by dillonkearns** [comment]
Thank you so much @Y0hy0h! A fix is live 👍

**Comment by Y0hy0h** [comment]
Thank you for fixing it so quickly! :)

By the way, elm-pages looks absolutely amazing! I can't wait to find an excuse and some time to try it out!
