### ISSUE TITLE
Vite 6 Support

### ISSUE THREAD

**Issue by lishaduck** [dillonkearns/elm-pages#497]
Just an FYI, Vite 6 was released today. You've got it constrained to v5, so it'll require at least a bump in the `package.json`.

I'd also assume that the new environment API is relevant for `elm-pages`, but I'd split the upgrade.

If you want a PR, I might find some time. It's not terribly important to me (I'm still on `elm-pages` v2 🤣), but I think it's worthwhile keeping up-to-date.

**Comment by dillonkearns** [comment]
Thanks for letting me know @lishaduck!

I think I've got things ready to go here 👍  https://github.com/dillonkearns/elm-pages/pull/498. Seems solid, I'll cut a new release. The only change is it drops support for some EOL Node versions, but that seems like a reasonable upgrade condition for a new NPM package release.
