### ISSUE TITLE
Do code-splitting on metadata

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-pages#54]
Provide an API for fetching exactly the metadata you need for each individual page. A pattern similar to the `StaticHttp` API would work nicely. You tell it at the top of the page if you need to grab any metadata. You can tell it exactly what metadata you want, and it will only include that metadata, and will bundle it into the `content.json` file for that page.

It might look something like this:

```elm
getBlogPostMetadata : Metadata -> Bool
getBlogPostMetadata metadata =
    case metadata of
        Metadata.Article articleMetadata ->
            True

        _ ->
            False
```

This is a nice pattern because user's are already doing exactly this... so it's ideal to have what you would naturally want to do just result in nice performance optimizations (rather than having to just write arbitrary code to optimize things).

Here's an example of some code that does something similar:

https://github.com/dillonkearns/elm-pages/blob/4ea2e47e9884129e8a464f24837c12fc95e528e4/examples/docs/src/Index.elm#L22-L31

It would be great to provide an API that also let's you return a `Maybe yourCustomType` rather than a `Bool` so that you can map over the items and narrow down the types (say, to only include blog posts and therefore narrow down the data type to that specific variant's data).

**Comment by BrianHicks** [comment]
> It would be great to provide an API that also let's you return a Maybe yourCustomType rather than a Bool so that you can map over the items and narrow down the types (say, to only include blog posts and therefore narrow down the data type to that specific variant's data).

I think this should be done sooner rather than later! I also think it would make most sense to have a custom constructor:

```elm
type Include metadata
    = Include metadata
    | Ignore

getMetadata : Metadata -> Include MySpecificMetadataShape
```

**Comment by dillonkearns** [comment]
The new `DataSource` API in the 2.0 NPM package/8.0 Elm package uses a pull-based approach to Metadata, so there's no more built-in notion of having pages' Metadata passed around. That means it can be split out as needed per-page (for example, only pull in blog posts' metadata for the blog index page, not any other pages' metadata). So this issue is now resolved! 🎉
