### ISSUE TITLE
Developer loop breaks when a code gen error happens.

### ISSUE THREAD

**Issue by rupertlssmith** [dillonkearns/elm-pages#56]
When running in dev mode if you get a compile error the dev loop keeps running. If you get a codegen error, say cannot decode your metadata, it breaks out of the dev loop and has to be manually restarted.

For example:

```
-- METADATA DECODE ERROR ----------------------------------------------------- elm-pages

I ran into a problem when parsing the metadata for the page with this path: /

Problem with the given value:

{
        "type": "news",
        "author": "Rupert Smith",
        "title": "Authentication in Elm",
        "description": "About and authentication API I designed for Elm.",
        "image": "/images/article-covers/hello.jpg",
        "published": "2020-01-21"
    }

Unexpected page type news
```

and then the dev loop terminates.

===

Would be nice if the dev loop just kept running - the error printed on the console is helpful in taking me right to the problem that needs to be fixed.

Bonus - if the error would also show in the browser.

**Comment by dillonkearns** [comment]
Released! https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-NPM.md#122---2020-01-27
