### ISSUE TITLE
Error running elm-pages build

### ISSUE THREAD

**Issue by nnelgxorz** [dillonkearns/elm-pages#64]
Hello!

I was trying to play around with elm-pages and ran into an error with the build command.

I set up a project with a directory structure like
- content
- images
- src
  - Main.elm

I dropped in a couple short test .md files into the content folder and some images into the image folder.

I then went to set up a Pages.Platform.application in my main function. I realized that I would need the generated elm-pages information to complete the record and the Manifest config. So, I threw an Html.text node in my main function and ran elm-pages build. I got the following error:

Running elm-pages...
(node:12200) UnhandledPromiseRejectionWarning: Error: What node should I take over? In JavaScript I need something like:

    Elm.Main.init({
        node: document.getElementById("elm-node")
    })

You need to do this with any Browser.sandbox or Browser.element program.
    at _Debug_crash (eval at <anonymous> (/home/glenn/.npm-global/lib/node_modules/elm-pages/generator/src/compile-elm.js:14:7), <anonymous>:550:10)
    at eval (eval at <anonymous> (/home/glenn/.npm-global/lib/node_modules/elm-pages/generator/src/compile-elm.js:14:7), <anonymous>:3940:56)
    at _Platform_initialize (eval at <anonymous> (/home/glenn/.npm-global/lib/node_modules/elm-pages/generator/src/compile-elm.js:14:7), <anonymous>:1879:16)
    at eval (eval at <anonymous> (/home/glenn/.npm-global/lib/node_modules/elm-pages/generator/src/compile-elm.js:14:7), <anonymous>:3928:9)
    at Object.eval [as init] (eval at <anonymous> (/home/glenn/.npm-global/lib/node_modules/elm-pages/generator/src/compile-elm.js:14:7), <anonymous>:20:33)
    at /home/glenn/.npm-global/lib/node_modules/elm-pages/generator/src/compile-elm.js:15:28
    at /home/glenn/.npm-global/lib/node_modules/elm-pages/generator/src/compile-elm.js:31:7
    at <anonymous>
(node:12200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I realize it's very likely I'm doing something wrong here. So, if this isn't a problem with elm-pages and is an issue with how I'm setting up my project, please let me know!

Thanks in advance!

**Comment by dillonkearns** [comment]
Hello!

Running `elm-pages develop` or `elm-pages build` depends on your `main` being an `elm-pages` program (so it can't just be Html or a sandbox application).

I would recommend using this starter template to get set up, it should be a lot easier! https://github.com/dillonkearns/elm-pages-starter

**Comment by nnelgxorz** [comment]
Thanks for the response, Dillon!

I was having npm related issues with the starter template, which is why I decided to try and start a project from scratch.

I sorted out the issues on my end and I have to say, elm-pages is an absolute joy. Thank you so much for all the hard work and love that has clearly gone into this!

**Comment by dillonkearns** [comment]
That's fantastic, I'm glad you resolved the issues! And thank you so much for the kind words, that's lovely to hear that you're enjoying it!

I've got a lot of exciting features that I'm working on, so stay tuned for more! I've got some ideas on how to simplify the application configuration as well, so that you don't have to pass in every configuration option until you need it.

What was the NPM issue you ran into related to? Was it something to do with sharp? Seems like some people are having to install libvips on mac to get past that.

**Comment by dillonkearns** [comment]
Yeah, I've heard others mention that. Probably adding a link in the readme, and in the readme for the elm-pages-starter repo would be a good starting point.

Did you have to install libvips or anything like that, or was it just simply deleting and re-running npm install for you?

**Comment by nnelgxorz** [comment]
Any guidance on that would be appreciated! I just deleted and re-installed and it worked.
