### ISSUE TITLE
Colorize "elm-pages build" output

### ISSUE THREAD

**Issue by ad-si** [dillonkearns/elm-pages#66]
Looks a little blunt right now 😉

![image](https://user-images.githubusercontent.com/36796532/73940132-ce597780-48e2-11ea-9ba0-564360f4dd9e.png)

**Comment by dillonkearns** [comment]
Hey! Thanks for reporting the issue, and good point.

Looks like it's related to this issue: https://github.com/rtfeldman/node-elm-compiler/issues/91.

That issue points out a hack that provides a workaround (by compiling it a second time if there's a failure). I guess I could fork the code and use that 🤷‍♂ Not great, but it would be nice to have nicely formatted error messages.

**Comment by ad-si** [comment]
Yesterday someone posted a solution without compiling twice: https://github.com/rtfeldman/node-elm-compiler/issues/91#issuecomment-583363707
Would this work for elm-pages?

**Comment by dillonkearns** [comment]
Wow, nice, thanks for that, I didn't see the new comment yesterday.

I'll see if I can fork that and try using that patch.

I'm both using the node-elm-compiler directly, and indirectly through the https://github.com/elm-community/elm-webpack-loader. But I can at least see if we can fix it in that one spot (which would fix the case that you took a screenshot of).

**Comment by dillonkearns** [comment]
It works!

![Image 2020-02-08 at 8 56 14 AM](https://user-images.githubusercontent.com/1384166/74088969-e3541900-4a50-11ea-853c-d4559fdd9b79.png)

**Comment by ad-si** [comment]
Awesome 👏, thanks!

**Comment by dillonkearns** [comment]
Just published! 😁 https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-NPM.md#128---2020-02-08

Note the caveat I mention in the changelog:

> Note, this patch still hasn't propogated through to `elm-webpack-loader` (see https://github.com/elm-community/elm-webpack-loader/issues/166).
> So there may still be non-colorized output for errors as you make changes while the dev server is running.

Hopefully this gets fixed upstream in `node-elm-compiler` and then `elm-webpack-loader` updates to pull in that change so we can get colorized output at that stage as well.
