### ISSUE TITLE
Instructions to setup and test the repo without resorting to npm link

### ISSUE THREAD

**Issue by leojpod** [dillonkearns/elm-pages#7]
Hi again and thanks for this great work! 

I'd be interested in trying to tweak things a bit and I was wondering what you are using to test `elm-pages` locally and if there are some setup steps required for it. 

Cheers

**Comment by dillonkearns** [comment]
Hello!

Yeah, so what I've been doing to iterate on changes locally is I just use the elm-pages.com site, which is [in the examples folder](https://github.com/dillonkearns/elm-pages/blob/master/examples/docs/src/Main.elm), to test out new changes. That app is wired up to use the NPM package and Elm package in master, so you can make changes to the JS or Elm code and it will show up there.

If you don't mind, could you just open up an issue to discuss ideas before diving in with pull requests? I would definitely welcome contributions, but I always prefer to have a little conversation first to make sure people don't do work that can't be merged in or requires extra work to make a bunch of changes.

Thanks for reaching out!

**Comment by leojpod** [comment]
Hi Dillon! 

Sure thing, well as you can guess I wanted to have a look at either using env variables or add an extra params to allow changing the port of the development stuff :) 

Then I wanted to give it a try and check how I can use elm-page for a small project of mine and see if I can get back some ideas or observations.

**Comment by dillonkearns** [comment]
Hi Leo,

Thanks for the info on that!

It would be awesome to have a PR on the port parameter! By the way, that code is using this library for parsing the CLI options, so you could take a look at this: https://package.elm-lang.org/packages/dillonkearns/elm-cli-options-parser/latest/

And be sure to run `npm run build` when you make changes to the Elm code for those to take effect: https://github.com/dillonkearns/elm-pages/blob/master/package.json#L8.

Regarding the environment variables, could you open another github issue so we can brainstorm on that? I've actually got some ideas on how to approach that with a nice, type-safe API, would love to explore some of those possibilities before we dive into writing the code for it!

And your feedback when you try out the framework would be very appreciated, too! Thanks Leo!

**Comment by dillonkearns** [comment]
Hello @leojpod! Just FYI, I captured the notes from your question here in a [CONTRIBUTING doc](https://github.com/dillonkearns/elm-pages/blob/master/CONTRIBUTING.md). I hope it's helpful for future contributors.

Thanks for the discussion! Feel free to open other issues to continue the threads about the pull request ideas we discussed here. And thanks again!

**Comment by leojpod** [comment]
Sorry I didn't have much time this past week. I hope to be able to play again with `elm-page` tomorrow or next week :) 
I'll see if I can get a bit of hacktober going to add the port thingy :) 

thanks a lot for the explanations, I'm looking forward to trying things out!

**Comment by dillonkearns** [comment]
Awesome, sounds great! And no worries, any amount of contributions is welcome, even just the discussion is appreciated! Always great to get feedback. Let me know if you run into anything that isn't clear from the contributing guide that you need to get things running!
